language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - cd thoughtinator
  - python -m pytest tests/ --cov-report term --cov=thoughtinator
after_success:
  - codecov
